# Generated by Django 4.2 on 2023-05-26 00:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('convenios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('especialidades', '0001_initial'),
        ('setores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45, null=True, verbose_name='Nome')),
                ('data_cadastro', models.DateField(blank=True, null=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(max_length=45, verbose_name='Sexo')),
                ('grupo_sanguineo', models.CharField(max_length=45, null=True, verbose_name='Grupo Sanguineo')),
                ('telefone', models.CharField(max_length=45, null=True, verbose_name='Telefone')),
                ('nome_mae', models.CharField(max_length=45, null=True, verbose_name='Nome da Mãe')),
                ('nome_pai', models.CharField(max_length=45, null=True, verbose_name='Nome do Pai')),
                ('cpf', models.CharField(max_length=14, null=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=45, null=True, verbose_name='RG')),
                ('registro_atualizado', models.DateTimeField(auto_now=True)),
                ('registro_criado', models.DateTimeField(auto_now_add=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='convenios.convenio')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidade')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='setores.setor')),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
    ]
