# Generated by Django 4.2 on 2023-05-26 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='grupo_sanguineo',
            field=models.CharField(default=1, max_length=45, verbose_name='Grupo Sanguineo'),
            preserve_default=False,
        ),
    ]
