# Generated by Django 4.2 on 2023-05-26 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_alter_pessoa_grupo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='Grupo Sanguineo'),
        ),
    ]
