# Generated by Django 4.2 on 2023-05-26 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('especialidades', '0001_initial'),
        ('convenios', '0001_initial'),
        ('setores', '0001_initial'),
        ('pessoas', '0003_alter_pessoa_grupo_sanguineo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='convenio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='convenios.convenio'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='especialidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidade'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pessoas', to='setores.setor'),
        ),
    ]
