# Generated by Django 4.2 on 2023-05-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0005_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
    ]
