# Generated by Django 4.2 on 2023-05-26 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0006_alter_pessoa_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome',
            field=models.CharField(default=1, max_length=45, verbose_name='Nome'),
            preserve_default=False,
        ),
    ]
