# Generated by Django 4.2 on 2023-05-26 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0008_alter_pessoa_cpf_alter_pessoa_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='sexo',
            field=models.CharField(blank=True, choices=[('MAS', 'Maculino'), ('FEM', 'Feminino')], max_length=45, null=True, verbose_name='Sexo'),
        ),
    ]
