# Generated by Django 4.2 on 2023-05-26 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0009_alter_pessoa_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='grupo_sanguineo',
            field=models.CharField(blank=True, choices=[('TIPO A+', 'A+'), ('TIPO B+', 'B+'), ('TIPO O+', 'O+'), ('TIPO AB+', 'AB+'), ('TIPO A-', 'A-'), ('TIPO B-', 'B-'), ('TIPO O-', 'O-'), ('TIPO AB-', 'AB-')], max_length=45, null=True, verbose_name='Grupo Sanguineo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(max_length=45, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                             '+99 99 99999-0000'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
