# Generated by Django 4.2 on 2023-05-26 02:44

from django.db import migrations, models
import django_cpf_cnpj.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0010_alter_pessoa_grupo_sanguineo_alter_pessoa_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='crm',
            field=models.CharField(default=1, max_length=45, verbose_name='CRM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=django_cpf_cnpj.fields.CPFField(max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
