# Generated by Django 4.2 on 2023-05-26 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0011_pessoa_crm_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='crm',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='CRM'),
        ),
    ]
