# Generated by Django 4.2 on 2023-05-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0013_alter_pessoa_nome_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(blank=True, default=1, max_length=45, verbose_name='Nome do Pai'),
            preserve_default=False,
        ),
    ]
