# Generated by Django 4.2 on 2023-05-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0014_alter_pessoa_nome_pai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='crm',
            field=models.CharField(default=1, max_length=45, verbose_name='CRM'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pai',
            field=models.CharField(max_length=45, null=True, verbose_name='Nome do Pai'),
        ),
    ]
